### ISSUE TITLE
Doesn't work when multiple linerange inputs present in one \lstinputlisting

### ISSUE THREAD

**Issue by dhutchis** [jubobs/lstautodedent#1]
Hi there,
  I discovered that autodedent fails in statements like

```
\lstinputlisting[linerange={Block1,Block2,Block3}]{file.fs}
```

The result compiles but the indentation is incorrect.

**Comment by dhutchis** [comment]
Separating the includes out as in

```
\lstinputlisting[linerange=Block1]{file.fs}
\lstinputlisting[linerange=Block2]{file.fs}
\lstinputlisting[linerange=Block3]{file.fs}
```

fixes it.

**Comment by jubobs** [comment]
Yes. `lstautodedent` is very primitive, insofar as it only looks at the very first line of the listing in order to determine how much whitespace should be gobbled at the beginning of each of the remaining lines shown. Unfortunately, I don't think that can be easily improved.
